name: deep-snow
channels:
  - pytorch 
  - conda-forge
dependencies:
  - pytorch
  - rioxarray
  - ipykernel
  - matplotlib
  - torchvision
  - nb_conda_kernels
  - seaborn
  - h5netcdf
  - planetary-computer
  - geopandas
  - odc-stac
  - tqdm
  - dask<2025.3.0 # temporarily exclude latest dask version https://github.com/opendatacube/odc-stac/issues/199
  
