name: ci

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          cache: true
          frozen: true
          activate-environment: true

      - name: Run test suite
        run: |
          pytest -q tests
